# Generated by Django 4.1.7 on 2023-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_recordfile_created_at_recordfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='abstract_file',
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='abstract/'),
        ),
    ]
