# Generated by Django 4.1.7 on 2023-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
