# Generated by Django 4.1.7 on 2023-10-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
