# Generated by Django 4.1.7 on 2023-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_recordfile_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
