# Generated by Django 4.1.7 on 2023-10-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_recordfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
