# Generated by Django 4.1.7 on 2023-10-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_recordfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordfile',
            old_name='file_name',
            new_name='record_file_name',
        ),
    ]
