# Generated by Django 4.1.7 on 2023-10-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_rename_file_name_recordfile_record_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='record_file_name',
            field=models.CharField(max_length=255),
        ),
    ]
