# Generated by Django 4.1.7 on 2023-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_record_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
