# Generated by Django 4.1.7 on 2023-10-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_recordfile_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='recordfile',
            name='download_count',
        ),
    ]
