# Generated by Django 4.1.7 on 2023-10-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_record_download_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.recordsfolder')),
            ],
        ),
    ]
