# Generated by Django 4.1.7 on 2023-10-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_recordsfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordsFolder',
        ),
    ]
