# Generated by Django 4.1.7 on 2023-10-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_record_user_alter_record_adviser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
