# Generated by Django 4.1.7 on 2023-10-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('records', '0028_alter_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advised_records', to='accounts.adviser'),
        ),
    ]
