# Generated by Django 4.1.7 on 2023-10-26 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0034_alter_record_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
