# Generated by Django 4.1.7 on 2023-09-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_remove_file_category_file_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_in_folder', to='file_management.file'),
        ),
    ]
