# Generated by Django 4.1.7 on 2023-09-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
