# Generated by Django 4.1.7 on 2023-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0006_folder_parent_folder_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
