# Generated by Django 4.1.7 on 2023-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0007_file_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
