# Generated by Django 4.1.7 on 2023-10-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('file_management', '0008_alter_file_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.classification'),
        ),
        migrations.AddField(
            model_name='folder',
            name='pscedclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.pscedclassification'),
        ),
    ]
