# Generated by Django 4.1.7 on 2023-10-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('file_management', '0010_subfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='pscedclassification',
        ),
        migrations.AddField(
            model_name='subfolder',
            name='pscedclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.pscedclassification'),
        ),
    ]
