# Generated by Django 4.1.7 on 2023-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0012_subfolder_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfolder',
            name='classification',
        ),
    ]
