# Generated by Django 4.1.7 on 2023-10-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('file_management', '0013_remove_subfolder_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfolder',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
    ]
