# Generated by Django 4.1.7 on 2023-10-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0014_subfolder_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subfolder',
            name='record',
        ),
    ]
