# Generated by Django 4.1.7 on 2023-10-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0016_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
