# Generated by Django 4.1.7 on 2023-10-17 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_access_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_management', '0018_remove_dashboard_access_count_loginevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
