# Generated by Django 4.1.7 on 2023-10-19 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_recordfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_management', '0019_recordaccessevent_delete_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedFileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_count', models.IntegerField(default=0)),
                ('access_time', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
