# Generated by Django 4.1.7 on 2023-10-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0021_uploadcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadCount',
        ),
    ]
