# Generated by Django 4.1.7 on 2023-10-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0023_uploadcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='log_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
