# Generated by Django 4.1.7 on 2023-10-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0024_loginevent_log_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedfileevent',
            name='delete_count',
        ),
    ]
