# Generated by Django 4.1.7 on 2023-10-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0028_studentfolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedfileevent',
            old_name='access_time',
            new_name='delete_time',
        ),
    ]
