# Generated by Django 4.1.7 on 2023-10-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('records', '0019_delete_recordsfolder'),
        ('file_management', '0030_downloadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfolder',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.record'),
        ),
        migrations.AddField(
            model_name='studentfolder',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrole'),
        ),
    ]
