# Generated by Django 4.1.7 on 2023-10-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_record_user_alter_record_adviser'),
        ('file_management', '0031_studentfolder_record_studentfolder_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfolder',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='records.record'),
        ),
    ]
