# Generated by Django 4.1 on 2023-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
